env: local

database:
  port: 5432
  driver: "postgres"
  user: user
  password: password
  database: db
  host: localhost
  ssl_mode: disable
  migrations_path: ./migrations

server:
  port: 8082

auth:
  client:
    grpc_address: "localhost:50051"
    timeout: 5s

storage:
  type: "minio"
  minio:
    endpoint: "localhost:9000"
    access_key_id: "minioadmin"
    secret_access_key: "minioadmin"
    use_ssl: false
    bucket_name: "dormitory-life"
    public_url: "http://localhost:9000"
