env: local

database:
  port: 5432
  driver: "postgres"
  user: user
  password: password
  database: db
  host: localhost
  ssl_mode: disable
  migrations_path: ./migrations

server:
  port: 8082

auth:
  client:
    grpc_address: "localhost:50051"
    timeout: 5s

storage:
  type: "minio"
  minio:
    endpoint: "localhost:9000"
    access_key_id: "minioadmin"
    secret_access_key: "minioadmin"
    use_ssl: false
    bucket_name: "dormitory-life"
    public_url: "http://localhost:9000"

broker:
  port: 5672
  host: "localhost"
  user: admin
  password: admin

broker_queues:
  support_queue: support_queue

emailer:
  host: smtp.mail.ru
  port: 587
  user: vladlim2003@mail.ru
  password: eaarK9LFd5KCzrFe0ALb
  email: vladlim2003@mail.ru
