env: local

database:
  port: 5432
  driver: "postgres"
  user: user
  password: password
  database: db
  host: localhost
  ssl_mode: disable
  migrations_path: ./migrations

server:
  port: 8082

auth:
  client:
    grpc_address: "localhost:50051"
    timeout: 5s
